export const promptsDaily = [
  "What made me smile today?",
  "How am I feeling right now, and why?",
  "What am I grateful for today?",
  "What do I need more of in my life?",
  "What's one thing I'm proud of this week?",
  "What's something I'm avoiding, and why?",
  "A moment today I want to remember",
  "What's one small thing I can do to take care of myself?",
  "If today were a color, what would it be and why?",
  "What's on my mind that I haven't said out loud?",
  "What do I need to let go of?",
  "What would I tell my past self right now?",
  "What's something I want to learn or try?",
  "A recent challenge and how I handled it",
  "How do I define success today?",
  "What do I want tomorrow to feel like?",
  "What's something that's working well in my life?",
  "If I had unlimited time today, what would I do?",
  "Who or what is inspiring me lately?",
  "What does my ideal day look like?",
];

export const promptsGratitude = [
  "What is something small I'm grateful for today?",
  "Who in my life am I especially thankful for right now?",
  "What is a recent experience that brought me joy?",
  "What physical ability do I feel grateful for?",
  "What is something in nature I'm thankful for?",
  "What is a past challenge I'm now grateful for?",
  "What's something about my home I appreciate?",
  "What technology makes my life easier or better?",
  "What's a favorite memory I'm thankful for?",
  "What is something about my body I'm grateful for?",
  "What's a simple pleasure I enjoyed recently?",
  "What's one thing I take for granted but truly value?",
  "What's something I'm grateful to have learned?",
  "Who made a positive impact on me this week?",
  "What's something I'm looking forward to and grateful for?",
  "What's a hobby or activity that brings me gratitude?",
  "What's a daily routine I appreciate?",
  "What's a book, movie, or song I'm thankful for?",
  "What's something about myself I'm proud of and grateful for?",
  "What's a kindness someone showed me recently?",
];
